<div class="d-flex flex-row">
    <?php include_once '../View/Template/dashboard_sidebar.php'; ?>
    <section class="flex-fill bg-white border ms-rounded m-3 px-3 py-5">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis in dui et ipsum aliquam lobortis. Etiam lobortis rutrum ex, vel semper dolor facilisis et. Vivamus vitae urna quis mauris auctor volutpat ullamcorper ut nisl. Cras rhoncus augue molestie, rhoncus velit nec, fermentum turpis. Nulla iaculis volutpat nibh, sed luctus quam sagittis vel. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec porttitor porttitor neque vitae volutpat. Curabitur lorem est, porttitor sed fermentum eu, efficitur at eros. Aenean molestie ligula sit amet orci ultricies, vulputate aliquam justo venenatis. Phasellus luctus dolor id consectetur interdum. Morbi dapibus semper lorem, in lobortis ante pellentesque vitae. Nunc euismod placerat fermentum. Praesent aliquam, metus ac hendrerit elementum, lorem lorem fermentum odio, in dapibus neque sem a nisl. Fusce rhoncus sapien sit amet vulputate auctor.

        Suspendisse vitae mauris venenatis, sollicitudin urna nec, congue lectus. Etiam et pellentesque felis. Proin posuere ornare dignissim. Etiam a egestas dolor. Curabitur at laoreet augue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean molestie velit eu odio viverra euismod. Nam id dui at elit tempus facilisis non nec nisl. Fusce urna lacus, convallis ut odio feugiat, tincidunt pellentesque risus.

        Sed id sem in urna tempor consequat. Vivamus semper nisl quis arcu malesuada, vitae porttitor lectus rutrum. Aenean fermentum nisl luctus volutpat pharetra. Phasellus luctus arcu est, ac pellentesque massa accumsan id. Fusce elit mi, dignissim eu convallis auctor, pharetra quis turpis. Donec vel congue nisl, ut molestie ipsum. Integer dictum imperdiet dictum. Donec dui velit, scelerisque vitae purus maximus, ornare placerat magna. Suspendisse suscipit sagittis urna id elementum. Integer feugiat nunc non purus cursus posuere. Nam eget diam sem.

        Nunc eu euismod erat, pharetra porttitor mi. Etiam at felis eget urna euismod facilisis. Nulla fringilla, nisi vel aliquet tristique, nulla mauris bibendum elit, fermentum luctus nisl arcu pulvinar risus. Mauris nec quam laoreet, tristique leo a, tempus elit. Integer quis risus facilisis, laoreet nunc et, condimentum est. Sed posuere, purus sit amet commodo pharetra, massa velit pharetra nisl, id sollicitudin justo eros cursus nunc. In ut urna risus. Sed fermentum lectus ut libero lacinia, at aliquam tortor iaculis. Morbi consequat convallis mi, at sollicitudin urna ullamcorper in. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris sit amet ultrices ligula.

        Etiam accumsan porta volutpat. Cras et augue quis augue mollis commodo. Morbi efficitur eu nibh at consequat. Donec pulvinar placerat ex, ac rhoncus lorem iaculis ut. Nam felis lacus, blandit efficitur nunc non, eleifend hendrerit ipsum. Vivamus vel sagittis est. Nullam sit amet dapibus eros. Phasellus enim dui, lacinia nec pulvinar nec, porttitor vel lorem. Curabitur in dapibus mi, quis accumsan sapien. Ut urna enim, feugiat sit amet velit sit amet, bibendum cursus augue. Vivamus lorem ligula, tincidunt at nulla ut, accumsan feugiat sapien. Integer molestie vitae ipsum scelerisque tincidunt. Vestibulum velit nibh, gravida a lectus quis, posuere faucibus eros. Fusce justo leo, ultrices ut dui in, posuere bibendum mauris.

        Duis at dapibus purus, vel malesuada ex. Mauris venenatis vel diam eu bibendum. Aenean nec arcu eu augue rutrum accumsan. Cras elit magna, finibus eget turpis tincidunt, convallis lobortis ligula. Nam in nibh metus. Integer non sagittis tortor. Quisque iaculis fermentum erat, et volutpat massa venenatis ut. Cras id egestas sapien. Donec sem ipsum, eleifend quis lobortis quis, sollicitudin quis velit. Quisque dolor turpis, fermentum elementum lacus ut, luctus facilisis nisl. Integer in tortor bibendum, cursus est vel, ullamcorper orci. Nam libero libero, dictum sit amet tempus vel, volutpat vitae augue.

        Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras scelerisque vitae turpis a mollis. Quisque vel mollis purus. Proin posuere ultricies neque, vel bibendum justo bibendum at. In a sapien non diam aliquam faucibus nec ut sapien. Sed pellentesque ligula sit amet gravida tincidunt. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse luctus eros nec nisi ullamcorper, quis laoreet nisl hendrerit. Nunc porta odio erat, in dictum dui rutrum posuere. Suspendisse vitae maximus justo. Curabitur lobortis facilisis semper. Integer ut dui fermentum, lobortis est eget, faucibus felis.

        Nullam eu aliquet odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam eleifend, ex nec condimentum aliquet, dolor lorem varius lorem, eu rutrum est arcu vitae justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec odio est, ultricies nec elementum quis, sodales eget arcu. Fusce ultrices, ante nec efficitur finibus, felis nibh molestie odio, vel accumsan tellus felis a eros. Sed quis eleifend sem. Etiam ut facilisis nibh, non molestie metus. Maecenas leo neque, viverra vitae euismod mollis, tempor malesuada metus. Quisque nisi est, sollicitudin et eros vel, pellentesque varius orci. Vestibulum nunc ipsum, commodo vitae posuere ac, lobortis nec purus.

        Nulla vestibulum aliquet efficitur. Integer rhoncus urna mauris, at viverra metus pulvinar a. In commodo euismod justo, vitae venenatis lorem venenatis eu. Curabitur finibus, sem nec dapibus porta, ligula nulla dapibus mi, non ullamcorper lorem justo sit amet odio. Phasellus hendrerit sollicitudin ipsum, non ornare neque elementum sed. Ut a magna eu ante ullamcorper malesuada. Quisque cursus pellentesque ex at suscipit. Sed non facilisis turpis, non ultrices urna. Vestibulum vestibulum ultrices ante, et dapibus lacus sollicitudin nec. Aenean vitae convallis sem, vitae dignissim justo. In congue placerat dapibus. Fusce et suscipit dolor, vitae elementum purus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam eu bibendum turpis.

        Ut a interdum mauris. Etiam blandit augue pretium sapien mattis, in hendrerit nibh facilisis. Donec pulvinar nisi libero. Fusce sit amet tristique leo, sed tristique nibh. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas nec diam pharetra, facilisis ex et, dictum nisi. Vestibulum lectus massa, dictum in nibh nec, semper placerat ipsum. In erat risus, lacinia sed congue at, tempor et arcu. Nunc eget sem id enim faucibus volutpat ac non lacus. Morbi id urna dui.

        Nam ullamcorper consequat nisi, sed dignissim ipsum elementum in. Curabitur pharetra libero sed eros rhoncus iaculis. Vivamus non consectetur nisi, nec venenatis augue. Suspendisse eget lacus ultricies, pretium turpis in, blandit risus. Aliquam tellus magna, facilisis in elit sit amet, volutpat venenatis lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer condimentum, risus ac dapibus congue, quam nunc laoreet magna, eget venenatis sem arcu non mauris. Nulla aliquam luctus nulla, eget laoreet turpis venenatis quis. Donec in augue nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed varius maximus iaculis. Etiam laoreet finibus venenatis. Vivamus porta leo sed velit molestie, vel bibendum massa dignissim. Donec tortor neque, placerat at odio sed, posuere lobortis turpis. Nulla facilisi. Nullam ac condimentum sem, non pellentesque turpis.

        Phasellus vitae massa eros. Nunc congue euismod metus, vitae hendrerit felis venenatis eu. Mauris rhoncus tortor vel justo molestie fermentum. Sed cursus viverra tortor ac suscipit. Nunc fringilla pulvinar ipsum in tincidunt. Sed mollis justo in nibh cursus tincidunt. Sed laoreet arcu et orci bibendum hendrerit. Etiam bibendum libero vitae pellentesque ullamcorper. Suspendisse ante felis, sodales id sapien vitae, scelerisque venenatis nunc. Morbi euismod laoreet enim, at imperdiet sem sodales a. Curabitur vitae aliquet turpis. Duis in egestas neque. Mauris blandit risus augue, tempor efficitur velit rutrum blandit. Donec mollis massa sed feugiat facilisis.

        Vestibulum convallis quam ex, suscipit auctor odio porta non. Donec vestibulum lorem quis mauris eleifend, in eleifend orci porttitor. In gravida metus ipsum, nec blandit mi dictum nec. In aliquet eget dui vel volutpat. Sed quis turpis diam. Maecenas imperdiet feugiat lorem, sit amet vulputate nibh congue eu. Maecenas sollicitudin velit ac condimentum interdum. Curabitur pharetra, leo vitae molestie iaculis, orci felis ultrices nunc, non euismod quam metus sed felis. In justo metus, pretium in nulla id, sollicitudin efficitur turpis. Fusce lacus quam, hendrerit eu odio vitae, tincidunt auctor sapien. Suspendisse semper interdum velit, id imperdiet erat aliquam id. Sed dapibus nisi mauris, non consectetur lorem imperdiet et. Suspendisse ante nisi, dapibus vel risus vel, scelerisque suscipit mi.

        Maecenas ultricies ut quam ac congue. Integer sit amet nisi in felis dictum bibendum. Duis pellentesque dolor a imperdiet scelerisque. Nulla condimentum quam a condimentum rutrum. Vivamus sit amet accumsan dolor. Sed at tempus purus, vitae vestibulum enim. Nulla facilisi. Sed eleifend, quam lobortis mattis auctor, orci urna bibendum odio, tristique sollicitudin magna libero feugiat sapien. Proin massa quam, euismod tristique nunc ut, sollicitudin hendrerit neque. Integer magna dolor, commodo ac ligula eget, vulputate volutpat massa. Phasellus leo dui, molestie ac metus nec, sollicitudin facilisis sapien. Nam quis enim a ante fringilla ultrices.

        Duis est nulla, tincidunt vel tincidunt vel, cursus quis leo. Cras sit amet scelerisque ipsum. Quisque at ex enim. Proin non dignissim justo. Nulla quis lobortis sapien, vitae venenatis ipsum. In ut luctus neque. Morbi posuere mi quis lectus blandit dignissim nec quis augue. Suspendisse vehicula auctor velit vitae auctor. Sed at euismod nibh, non scelerisque orci. Donec luctus commodo urna bibendum sodales. Pellentesque at porta purus. Sed est elit, rhoncus sed quam sit amet, vestibulum aliquet urna. Maecenas sollicitudin quam vitae orci placerat, ac tempus elit sagittis. Nam auctor, justo eu tincidunt tempor, leo lorem interdum magna, in accumsan erat lacus vitae ante. Etiam odio justo, pharetra id porttitor eget, scelerisque non augue.
    </section>
</div>